# Copyright (C) 2026  A. Iooss
# SPDX-License-Identifier: CC0-1.0
services:
  suricata:
    build: ./suricata
    image: ghcr.io/fcsc-fr/shovel/suricata:dev
    volumes:
      # Only needed in mode A
      - "./input_pcaps:/input_pcaps:ro"
      # Optional: makes rule editing easier
      - "./suricata/rules:/suricata/rules:ro"
      # Only needed for pcap output
      - "./output_suricata:/output_suricata:rw"

    # Mode A: pcap replay mode (slower, for archives replay or rootless CTF)
    # Add `--pcap-file-continuous` to watch for new pcap in folder.
    # command: -r /input_pcaps --pcap-file-continuous

    # Mode B: capture interface (fast, requires root on vulnbox and in Docker)
    # Drastically reduces ingest delay, but requires to setup traffic mirroring
    # between the vulnbox game interface and a team server.
    #command: -i tun5
    #cap_add:
    #  - NET_ADMIN
    #environment:
    #  - PCAP_LOG=yes
    #network_mode: "host"

    # Mode C: PCAP-over-IP (fast, requires root on vulnbox)
    # Connects to a PCAP-over-IP server, such as pcap-broker to read PCAP data.
    command: -r /dev/stdin
    restart: on-failure
    depends_on:
      - pcap-broker
    environment:
      - PCAP_LOG=yes
      - PCAP_OVER_IP=pcap-broker:4242
      - DATABASE_URL=postgres://shovel:unsecure_password@db/shovel

  webapp:
    build: ./webapp
    image: ghcr.io/fcsc-fr/shovel/webapp:dev
    restart: on-failure
    volumes:
      # Only needed for pcap download
      - "./output_suricata:/output_suricata:rw"
    ports:
      - 8080:8000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://shovel:unsecure_password@db/shovel

  # Grafana default credentials are admin:admin
  grafana:
    build: ./grafana
    image: ghcr.io/fcsc-fr/shovel/grafana:dev
    restart: on-failure
    # Uncomment the following line if you want persistence
    #volumes: ["grafana-storage:/var/lib/grafana"]
    environment:
      # Warning: in production give read-only permissions to this user
      - POSTGRES_HOST=db:5432
      - POSTGRES_USER=shovel
      - POSTGRES_PASSWORD=unsecure_password
      - POSTGRES_DATABASE=shovel
    ports:
      - 3000:3000
    env_file:
      - .env

  # Database data persist in an anonymous volume
  # Data will be drop on `docker compose down`!!
  db:
    image: docker.io/library/postgres:18
    restart: on-failure
    environment:
      - POSTGRES_USER=shovel
      - POSTGRES_PASSWORD=unsecure_password

  pcap-broker:
    container_name: pcap-broker
    build:
      context: .
      dockerfile_inline: |
        FROM golang:alpine
        RUN apk add --no-cache build-base libpcap-dev openssh-client tcpdump
        RUN go install github.com/fox-it/pcap-broker@latest
        ENTRYPOINT ["pcap-broker"]
    restart: on-failure
    volumes:
      - "~/.ssh/id_vulnbox:/root/.ssh/id_ed25519:ro"
    environment:
      PCAP_COMMAND: |-
          ssh root@10.67.1.2 -oStrictHostKeyChecking=no
          tcpdump -U --immediate-mode -ni wg0 -s 65535 -w - not tcp port 22 and not tcp port 8080 and not tcp port 9100
      LISTEN_ADDRESS: 0.0.0.0:4242

volumes:
  grafana-storage: {}
