# Copyright (C) 2026  A. Iooss
# SPDX-License-Identifier: CC0-1.0
apiVersion: 1

datasources:
  - name: postgresql
    type: postgres
    url: ${POSTGRES_HOST}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DATABASE}
      sslmode: disable
      postgresVersion: 1500
    isDefault: true
