{
 "title": "Home",
 "time": { "from": "$CTF_START_DATE", "to": "2030-01-01T12:00:00.000Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "CTF_START_DATE", "label": "Start date", "query": "$CTF_START_DATE" },
   { "name": "CTF_TICK_LENGTH", "label": "Tick length", "query": "$CTF_TICK_LENGTH" },
   { "name": "CTF_SHOVEL_URL", "label": "Shovel host", "query": "$CTF_SHOVEL_URL" },
   { "name": "CTF_SERVICES", "label": "Services", "query": "$CTF_SERVICES" }
  ]
 },
 "panels": [
  {
   "title": "Flows per tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "WITH config AS (SELECT \n    (1000000 * EXTRACT(EPOCH FROM '${CTF_START_DATE}'::timestamp)) AS ctf_start_ts,\n    (1000000 * '${CTF_TICK_LENGTH}'::bigint) AS tick_length\n)\nSELECT\n    MIN(ts_start) / 1000000 AS time,\n    MIN(FLOOR((ts_start - ctf_start_ts) / tick_length)) as tick,\n    COUNT(*) as flows,\n    MIN(ctf_start_ts + FLOOR((ts_start - ctf_start_ts) / tick_length + 1) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start * 1000 >= $__unixEpochNanoFrom() and ts_start * 1000 < $__unixEpochNanoTo()\n    AND (CONCAT(src_ip, ':', src_port) IN (${CTF_SERVICES:singlequote}) OR CONCAT(dest_ip, ':', dest_port) IN (${CTF_SERVICES:singlequote}))\nGROUP BY FLOOR((ts_start - ctf_start_ts) / tick_length)"
    }
   ]
  },
  {
   "title": "FLAG IN/OUT per tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "WITH config AS (SELECT \n    (1000000 * EXTRACT(EPOCH FROM '${CTF_START_DATE}'::timestamp)) AS ctf_start_ts,\n    (1000000 * '${CTF_TICK_LENGTH}'::bigint) AS tick_length\n)\nSELECT\n    MIN(ts_start) / 1000000 AS time,\n    MIN(FLOOR((ts_start - ctf_start_ts) / tick_length)) as tick,\n    COUNT(*) as flag_out,\n    MIN(ctf_start_ts + FLOOR((ts_start - ctf_start_ts) / tick_length + 1) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start * 1000 >= $__unixEpochNanoFrom() and ts_start * 1000 < $__unixEpochNanoTo()\n    AND id IN (SELECT flow_id FROM alert WHERE tag = 'FLAG OUT')\n    AND (CONCAT(src_ip, ':', src_port) IN (${CTF_SERVICES:singlequote}) OR CONCAT(dest_ip, ':', dest_port) IN (${CTF_SERVICES:singlequote}))\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n"
    },
    {
     "dataset": "shovel",
     "rawSql": "WITH config AS (SELECT \n    (1000000 * EXTRACT(EPOCH FROM '${CTF_START_DATE}'::timestamp)) AS ctf_start_ts,\n    (1000000 * '${CTF_TICK_LENGTH}'::bigint) AS tick_length\n)\nSELECT\n    MIN(ts_start) / 1000000 AS time,\n    MIN(FLOOR((ts_start - ctf_start_ts) / tick_length)) as tick,\n    COUNT(*) as flag_in,\n    MIN(ctf_start_ts + FLOOR((ts_start - ctf_start_ts) / tick_length + 1) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start * 1000 >= $__unixEpochNanoFrom() and ts_start * 1000 < $__unixEpochNanoTo()\n    AND id IN (SELECT flow_id FROM alert WHERE tag = 'FLAG IN')\n    AND (CONCAT(src_ip, ':', src_port) IN (${CTF_SERVICES:singlequote}) OR CONCAT(dest_ip, ':', dest_port) IN (${CTF_SERVICES:singlequote}))\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n"
    }
   ]
  },
  {
   "title": "Last flags IN/OUT",
   "type": "logs",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "shovel",
     "rawSql": "WITH config AS (SELECT \n    (1000000 * EXTRACT(EPOCH FROM '${CTF_START_DATE}'::timestamp)) AS ctf_start_ts,\n    (1000000 * '${CTF_TICK_LENGTH}'::bigint) AS tick_length\n)\nSELECT\n    ts_start / 1000000 AS time,\n    concat('tick=', (ts_start - ctf_start_ts) / tick_length, ' ', metadata#>>'{flowvars,0,match}') AS text\nFROM flow, config\nWHERE\n    ts_start * 1000 >= $__unixEpochNanoFrom() and ts_start * 1000 < $__unixEpochNanoTo()\n    AND metadata#>>'{flowvars,0,match}' IS NOT NULL\n    AND (CONCAT(src_ip, ':', src_port) IN (${CTF_SERVICES:singlequote}) OR CONCAT(dest_ip, ':', dest_port) IN (${CTF_SERVICES:singlequote}))\nORDER BY ts_start DESC\nLIMIT 1000"
    }
   ]
  }
 ]
}